example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = "example_app"

urlpatterns = [
    path("", index, name="index"),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("example_app.urls")),
    path("wishlist/", include("wishlist.urls")),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import (
    show_wishlist,
    show_xml,
    show_json,
    register,
    login_user,
    logout_user,
    show_wishlist_ajax,
    add_wishlist_ajax
)

app_name = "wishlist"

urlpatterns = [
    path("", show_wishlist, name="show_wishlist"),
    path("xml/", show_xml, name="show_xml"),
    path("json/", show_json, name="show_json"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("ajax/", show_wishlist_ajax, name="show_wishlist_ajax"),
    path("ajax/post/", add_wishlist_ajax, name="add_wishlist_ajax")
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models


class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")

wishlist/views.py
import datetime
from django.shortcuts import render, redirect
from wishlist.models import BarangWishlist
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url="/wishlist/login/")
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        "list_barang": data_barang_wishlist,
        "last_login": request.COOKIES.get("last_login"),
        "logged_in": request.user.is_authenticated,
    }
    return render(request, "wishlist.html", context)

@login_required(login_url="/wishlist/login/")
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        "list_barang": data_barang_wishlist,
        "last_login": request.COOKIES.get("last_login"),
        "logged_in": request.user.is_authenticated,
    }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url="/wishlist/login/")
def add_wishlist_ajax(request):
    if request.method == "POST":
        nama_barang = request.POST.get("nama_barang")
        harga_barang = request.POST.get("harga_barang")
        deskripsi = request.POST.get("deskripsi")
        barang = BarangWishlist(
            nama_barang=nama_barang,
            harga_barang=harga_barang,
            deskripsi=deskripsi,
        )
        barang.save()
        return redirect("wishlist:show_wishlist_ajax")
    else:
        return redirect("wishlist:show_wishlist_ajax")

def show_xml(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    data = serializers.serialize("xml", data_barang_wishlist)
    return HttpResponse(data, content_type="text/xml")


def show_json(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    data = serializers.serialize("json", data_barang_wishlist)
    return HttpResponse(data, content_type="application/json")


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Akun telah berhasil dibuat!")
            return redirect("wishlist:login")
        else:
            messages.error(request, 'Akun gagal dibuat!')

    context = {"form": form}
    return render(request, "register.html", context)


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist"))
            response.set_cookie("last_login", str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, "Username atau Password salah!")
    context = {}
    return render(request, "login.html", context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse("wishlist:login"))
    response.delete_cookie("last_login")
    return redirect("wishlist:login")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://cdn.tailwindcss.com"></script>
    {% block meta %} {% endblock meta %}
  </head>

  <body class="bg-gray-200">
    <nav
      class="w-full h-16 md:h-20 px-6 md:px-8 flex flex-row justify-between items-center bg-blue-300 shadow-lg"
    >
      <h1 class="font-bold text-xl md:text-2xl">Mohammad Ferry Husnil Arif 🗿</h1>
      {% if logged_in %}
      <a
        class="border border-blue-600 border-2 rounded-xl px-2 md:px-3 py-1 shadow-lg text-base md:text-lg hover:bg-blue-600 hover:text-white transition duration-200"
        href="{% url 'wishlist:logout' %}"
        >Logout</a
      >
      {% endif %}
    </nav>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/wishlist.html
{% extends 'base.html' %} {% block content %}
<h5>Nama:</h5>
<b>{{nama}}</b>

<table>
  <tr>
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
  </tr>
  {% comment %} Tambahkan data di bawah baris ini {% endcomment %} 
  {% for barang in list_barang %}
  <tr>
    <th>{{barang.nama_barang}}</th>
    <th>{{barang.harga_barang}}</th>
    <th>{{barang.deskripsi}}</th>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

wishlist/templates/login.html
{% extends 'base.html' %} {% block meta %}
<title>Login</title>
{% endblock meta %} {% block content %}

<div class="login">
  <h1>Login</h1>

  <form method="POST" action="">
    {% csrf_token %}
    <table>
      <tr>
        <td>Username:</td>
        <td>
          <input
            type="text"
            name="username"
            placeholder="Username"
            class="form-control"
          />
        </td>
      </tr>

      <tr>
        <td>Password:</td>
        <td>
          <input
            type="password"
            name="password"
            placeholder="Password"
            class="form-control"
          />
        </td>
      </tr>

      <tr>
        <td></td>
        <td><input class="btn login_btn" type="submit" value="Login" /></td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %} Belum mempunyai akun?
  <a href="{% url 'wishlist:register' %}">Buat Akun</a>
</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %} {% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %} {% block content %}

<div class="login">
  <h1>Formulir Registrasi</h1>

  <form method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td><input type="submit" name="submit" value="Daftar" /></td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %} {% block content %}

<main class="w-screen my-24 flex flex-col items-center">
  <table class="w-5/6 text-center">
    <tr class="bg-blue-600 md:text-lg text-white">
      <th class="p-3 rounded-tl-lg">Nama Barang</th>
      <th class="p-3">Harga Barang</th>
      <th class="p-3 rounded-tr-lg">Deskripsi</th>
    </tr>
    {% for barang in list_barang %}
    <tr class="text-sm md:text-base">
      <td class="p-2">{{barang.nama_barang}}</td>
      <td class="p-2">{{barang.harga_barang}}</td>
      <td class="p-2">{{barang.deskripsi}}</td>
    </tr>
    {% endfor %}
  </table>
  <h5 class="mt-24 font-bold">Sesi terakhir login: {{ last_login }}</h5>
</main>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %} 

{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
    $(document).ready(function(){
      $("#get-data").click(function(){
        $.get(window.location.href.replace("ajax", "json"), function(data) {
          $("#wishlist-data").empty();
          data.forEach(function(item) {
            $("#wishlist-data").append(
              `<tr>
                <td>${item.fields.nama_barang}</td>
                <td>${item.fields.harga_barang}</td>
                <td>${item.fields.deskripsi}</td>
              </tr>`
            );
          });
        });
      });
    });

    function postAjax() {
      $("form#wishlist-form").submit(function (e) {
            e.preventDefault();
            var actionURL = event.currentTarget.action;
            var formData = $("form#wishlist-form").serialize();
            console.log(formData);
            $.ajax({
                url: actionURL,
                type: "POST",
                data: formData,
                success: (data) => {
                    alert("success!");
                },
                error: (error) => {
                    console.log(error);
                    alert("Error!");
                }
            });
        });
    }

    </script>
{% endblock meta %}

{% block content %}

<table>
  <thead>
    <tr>
      <th>Nama Barang</th>
      <th>Harga Barang</th>
      <th>Deskripsi</th>
    </tr>
  </thead>
  <tbody id="wishlist-data">
  </tbody>
</table>

<button id="get-data">Get data</button>

<form method="POST" action="{% url 'wishlist:add_wishlist_ajax' %}" id="wishlist-form">
  {% csrf_token %}
  <input type="text" name="nama_barang" placeholder="Nama Barang" />
  <input type="number" name="harga_barang" placeholder="Harga Barang" />
  <input type="text" name="deskripsi" placeholder="Deskripsi" />
  <input type="submit" value="Tambah" />
</form>

{% endblock content %}